.TH "ruiji" "1" "Jan 05 2017" "\ \&" "\ \&"

.SH "NAME"
ruiji \- reverse image searching program using iqdb.org

.SH "SYNOPSIS"
ruiji [options] [image file]

.SH "OPTIONS"
.sp
.PP
\fB\-f, --file=[FILENAME]\fR
.RS 4
Takes in the given file to upload\&.
.RE
.PP
\fB\-h, --help\fR
.RS 4
Show help message and quit\&.
.RE
.PP
\fB\-q, --quiet\fR
.RS 4
Suppress verbose output (currently, doesn't work)\&.
.RE
.PP
\fB\-t, --threshold=<0-100>\fR
.RS 4
Only show images above certain similarity percentage (default: 0)\&.
.RE
.PP
\fB\-v, --version\fR
.RS 4
Show version number and quit\&.
.RE
.PP
\fB\-y, --noprompt\fR
.RS 4
Skips user interactions and downloads the most similar image\&.
.RE
.PP

.SH "DESCRIPTION"
Command that uploads a supported image format to http://iqdb.org, parses the subsequent html for similar image results and prompt the user which one to download.

