#include "danbooru.h"
#include "eshuushuu.h"
#include "gelbooru.h"
#include "konachan.h"
#include "sankakucomplex.h"
#include "yandere.h"
#include "zerochan.h"

#define IQDB_URL "https://iqdb.org"

#define DANBOORU_DOMAIN "danbooru.donmai.us"
#define ESHUUSHUU_DOMAIN "e-shuushuu.net"
#define GELBOORU_DOMAIN "gelbooru.com"
#define KONACHAN_DOMAIN "konachan.com"
#define SANKAKU_COMPLEX_DOMAIN "chan.sankakucomplex.com"
#define YANDERE_DOMAIN "yande.re"
#define ZEROCHAN_DOMAIN "www.zerochan.net"
